# Prerequisite Graph
This notebook models Berkeley course prerequisites as a directed graph. Each edge points from a prerequisite course to the course it unlocks.

## 1. Load Prerequisite Data

In [2]:
import pandas as pd
import networkx as nx

prereqs = pd.read_csv(
    "../data/processed/prerequisites_fall_2026.csv"
)

prereqs.head()

   course_id  subject course_number prereq_subject prereq_number
0     162181  AEROENG            10           MATH            51
1     162181  AEROENG            10           MATH            52
2     162181  AEROENG            10           MATH            53
3     162181  AEROENG            10        PHYSICS            7A
4     162181  AEROENG            10        COMPSCI           61A

## 2. Create Course Labels

In [4]:
prereqs["course"] = (
    prereqs["subject"] + " " + prereqs["course_number"].astype(str)
)

prereqs["prerequisite"] = (
    prereqs["prereq_subject"] + " " + prereqs["prereq_number"].astype(str)
)

prereqs.head()

,course_id,subject,course_number,prereq_subject,prereq_number,course,prerequisite
0,162181,AEROENG,10,MATH,51,AEROENG 10,MATH 51
1,162181,AEROENG,10,MATH,52,AEROENG 10,MATH 52
2,162181,AEROENG,10,MATH,53,AEROENG 10,MATH 53
3,162181,AEROENG,10,PHYSICS,7A,AEROENG 10,PHYSICS 7A
4,162181,AEROENG,10,COMPSCI,61A,AEROENG 10,COMPSCI 61A

## 3. Build Directed Graph

In [5]:
G = nx.DiGraph()

for _, row in prereqs.iterrows():
    G.add_edge(
        row["prerequisite"],
        row["course"]
    )

In [6]:
G.number_of_nodes(), G.number_of_edges()

(645, 1028)

In [7]:
list(G.predecessors("AEROENG 10"))

['MATH 51', 'MATH 52', 'MATH 53', 'PHYSICS 7A', 'COMPSCI 61A', 'ENGIN 7']

In [17]:
list(G.successors("COMPSCI 61B"))[:20]

['COMPSCI 160',
 'COMPSCI 161',
 'COMPSCI 162',
 'COMPSCI 164',
 'COMPSCI 168',
 'COMPSCI 169A',
 'COMPSCI 170',
 'COMPSCI 180',
 'COMPSCI 184',
 'COMPSCI 188',
 'COMPSCI 47A',
 'DATA C182',
 'DATA C101',
 'BIOENG C106A']

### Graph Observations
- Each node represents a Berkeley course.
- Directed edges represent prerequisite relationships. 
- Predecessors of a course represent its parsed prerequisites.
- Successors of a course represent courses that the prerequisite helps unlock.